//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyFlores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillaproduccion
    {
        public int idplanillaprodu { get; set; }
        public string tipoflor { get; set; }
        public System.DateTime fechasiembra { get; set; }
        public System.DateTime fechaterminación { get; set; }
        public int numerofloresaprobadas { get; set; }
        public int nfloresnoaprobadas { get; set; }
        public int cedula { get; set; }
        public int invernadero { get; set; }
    
        public virtual invernadero invernadero1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
