//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyFlores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class probloque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public probloque()
        {
            this.planillafertirriego = new HashSet<planillafertirriego>();
        }
    
        public int idbloque { get; set; }
        public int numerobloque { get; set; }
        public double presupuestadoaño { get; set; }
        public double llevamosaño { get; set; }
        public double diferenciaaño { get; set; }
        public double presupuestadomes { get; set; }
        public double llevamosmes { get; set; }
        public double diferenciames { get; set; }
        public int cedula { get; set; }
        public int idinvernadero { get; set; }
    
        public virtual invernadero invernadero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planillafertirriego> planillafertirriego { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
